import { Cursor } from '@/components/primitive/Cursor';
import { cn } from '@/lib/util';
import localFont from 'next/font/local';
import './globals.css';
import { Navbar } from '@/components/layout/Navbar/Navbar';
import { Footer } from '@/components/layout/Footer/Footer';
import { Noto_Serif } from 'next/font/google';

const sans = localFont({
  src: '../public/fonts/GeneralSans-Variable.ttf',
  variable: '--font-sans'
});

const serif = Noto_Serif({
  subsets: ['latin'],
  variable: '--font-serif'
});

const clashDisplay = localFont({
  src: '../public/fonts/ClashDisplay-Variable.ttf',
  variable: '--font-clashDisplay'
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          sans.variable,
          sans.className,
          serif.variable,
          clashDisplay.variable,
          'overflow-y-auto relative'
        )}
      >
        <div
          className="absolute inset-0 w-full h-full -z-20 opacity-[0.1] object-cover object-center blur-lg"
          style={{
            backgroundImage:
              'url(https://images.unsplash.com/photo-1686904423955-b928225c6488?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80)'
          }}
        ></div>
        <Navbar />
        <div id="fake-body">{children}</div>
        <Footer />

        <div className="fixed top-0 left-0 w-full h-full pointer-events-none z-50">
          <Cursor />
        </div>
        <div id="modal" className="z-40 absolute top-0 left-0" />
        <div id="image" className="z-50 absolute left-0 top-0" />
      </body>
    </html>
  );
}
