import { Cursor } from '@/components/primitive/Cursor';
import { cn } from '@/lib/util';
import { Inter, Noto_Serif } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';
import { Navbar } from '@/components/layout/Navbar/Navbar';
import { Footer } from '@/components/layout/Footer/Footer';

const notoSerif = Noto_Serif({
  subsets: ['latin'],
  variable: '--font-noto-serif',
  weight: ['400', '700']
});

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter'
});

const thunder = localFont({
  src: '../public/fonts/Thunder-SemiBold.ttf',
  variable: '--font-thunder'
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          inter.variable,
          thunder.variable,
          notoSerif.variable,
          'overflow-y-auto'
        )}
      >
        <Navbar className="bg-white" />
        <div id="fake-body">{children}</div>
        <Footer />

        <div className="fixed top-0 left-0 w-full h-full pointer-events-none z-50">
          <Cursor />
        </div>
        <div id="modal" className="z-40 absolute top-0 left-0" />
        <div id="image" className="z-50 absolute left-0 top-0" />
      </body>
    </html>
  );
}
